ONLY_ADMIN = 'Solo un administrador puede ejecutar este comando'
ONLY_GROUPS = 'Este comando solo está disponible en los grupos'
INVALID_SHEET = 'El link a la hoja de google no es válido. Asegurate de copiarlo bien y vuelve a ejecutar el comando de nuevo'
BOT_ADMIN = 'El bot debe ser administrador para ejecutar este comando'
NO_DB_GROUP = 'No has terminado de configurar el grupo. Usa /comprobar para ver lo que falta'
GROUP_CREATED = 'El grupo ha sido configurado con éxito!'
SHEET_UPDATED = 'La hoja ha sido actualizada con éxito!'